"""Shared runtime for generated API facades. Written once, by a platform team.

Every handler generated by `make codegen` calls `call()` to reach its API, so
these rules hold for every facade without each team re-implementing them:

- the API key comes from the worker's environment, never from the caller
- the Idempotency-Key is the handler workflow's ID, the same on every retry
- 4xx means the request is wrong: fail now (non-retryable)
- 5xx, 429 and connection errors mean the API is unhealthy: retry with backoff
"""

import json
import logging
from typing import Any, TypeVar

import httpx
from temporalio import activity
from temporalio.converter import DataConverter
from temporalio.exceptions import ApplicationError

T = TypeVar("T")
PERMANENT = {400, 401, 403, 404, 405, 409, 410, 422}
log = logging.getLogger("facade")


def to_wire(value: Any) -> dict:
    """A generated contract type as the JSON the API expects (unset fields omitted)."""
    payload = DataConverter.default.payload_converter.to_payloads([value])[0]
    return {k: v for k, v in json.loads(payload.data).items() if v is not None}


def from_wire(data: Any, type_: type[T]) -> T:
    """The API's JSON response as a generated contract type."""
    pc = DataConverter.default.payload_converter
    return pc.from_payloads(pc.to_payloads([data]), [type_])[0]


def _detail(resp: httpx.Response) -> str:
    try:
        body = resp.json()
        return body.get("detail", resp.text) if isinstance(body, dict) else resp.text
    except ValueError:
        return resp.text


async def call(
    *,
    base_url: str,
    method: str,
    path: str,
    body: dict | None,
    api_key_header: str | None,
    api_key: str | None,
    idempotency_header: str | None,
    timeout_s: float = 5,
) -> Any:
    """One HTTP call from inside an activity, with the retry decision made explicit."""
    info = activity.info()
    headers = {}
    if api_key_header and api_key:
        headers[api_key_header] = api_key
    if idempotency_header:
        headers[idempotency_header] = info.workflow_id  # stable across every retry of this call
    log.info("%s %s attempt=%d", method, path, info.attempt)

    async with httpx.AsyncClient(base_url=base_url, timeout=timeout_s) as http:
        try:
            resp = await http.request(method, path, json=body, headers=headers)
        except httpx.TransportError as e:
            log.warning("  -> unreachable (attempt %d)", info.attempt)
            raise ApplicationError(f"{base_url} unreachable: {e!r}", type="ApiUnavailable") from e

    if resp.is_error:
        log.warning("  -> %d %s (attempt %d)", resp.status_code, _detail(resp), info.attempt)
    if resp.status_code in PERMANENT:
        raise ApplicationError(
            f"API rejected the request ({resp.status_code}): {_detail(resp)}",
            type="ApiRejected",
            non_retryable=True,
        )
    if resp.is_error:
        raise ApplicationError(f"API error ({resp.status_code}): {_detail(resp)}", type="ApiUnavailable")
    return resp.json() if resp.content else None
