"""Generate a complete Nexus handler for an existing API from its OpenAPI spec.

For every route tagged `x-nexus` it writes, into the facade's handler package:
  activities.py  one activity per route: the HTTP call, via common/http_facade.py
  workflows.py   one workflow per route: retries the activity until the deadline
  worker.py      the Nexus service handler (async, workflow-backed) and its worker

Nothing in those files is written by hand. The API's owner tags routes; the
platform team owns common/http_facade.py; everyone else just calls the endpoint.

Usage: python scripts/gen_facade.py contracts/facades.yaml
"""

import json
import re
import sys
from pathlib import Path

import yaml

COMPONENT = "#/components/schemas/"


def q(value: str | None) -> str:
    return "None" if value is None else f'"{value}"'


def pascal(name: str) -> str:
    return "".join(p.capitalize() for p in re.split(r"[^a-zA-Z0-9]+", name) if p)


def snake(name: str) -> str:
    return re.sub(r"[^a-zA-Z0-9]+", "_", re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name)).lower().strip("_")


def routes(spec: dict) -> list[dict]:
    schemes = spec.get("components", {}).get("securitySchemes", {})
    found = []
    for path, methods in spec.get("paths", {}).items():
        for method, op in methods.items():
            nexus = op.get("x-nexus")
            if not nexus:
                continue
            body = op["requestBody"]["content"]["application/json"]["schema"]["$ref"].removeprefix(COMPONENT)
            ok = next(r for code, r in op["responses"].items() if code.startswith("2"))
            out = ok["content"]["application/json"]["schema"]["$ref"].removeprefix(COMPONENT)
            api_key_header = None
            for requirement in op.get("security", spec.get("security", [])):
                for name in requirement:
                    s = schemes.get(name, {})
                    if s.get("type") == "apiKey" and s.get("in") == "header":
                        api_key_header = s["name"]
            idem = next((p["name"] for p in op.get("parameters", [])
                         if p.get("in") == "header" and p["name"].lower() == "idempotency-key"), None)
            service = nexus["service"]
            found.append({
                "service": service,
                "service_class": pascal(service.split(".")[0]),
                "operation": nexus["operation"],
                "attr": snake(nexus["operation"]),
                "fn": f"{snake(service.split('.')[0])}_{snake(nexus['operation'])}",
                "workflow": f"{pascal(service.split('.')[0])}{pascal(nexus['operation'])}Workflow",
                "method": method.upper(),
                "path": path,
                "input": body,
                "output": out,
                "api_key_header": api_key_header,
                "idempotency_header": "Idempotency-Key" if idem else None,
            })
    return found


def header(src: str) -> str:
    return f"# GENERATED by scripts/gen_facade.py from {src}. Do not edit.\n# Regenerate with: make codegen\n"


def gen_activities(f: dict, rs: list[dict], src: str) -> str:
    types = sorted({r["input"] for r in rs} | {r["output"] for r in rs})
    out = [header(src), f'"""HTTP calls to the API, one activity per published route."""\n',
           "from temporalio import activity\n",
           "from common import config, http_facade",
           f"from {f['contract_module']} import {', '.join(types)}\n"]
    for r in rs:
        path = f'"{r["path"]}".format(**body)' if "{" in r["path"] else f'"{r["path"]}"'
        out.append(f'''
@activity.defn(name="{r['service']}.{r['operation']}")
async def {r['fn']}(req: {r['input']}) -> {r['output']}:
    """{r['method']} {r['path']}"""
    body = http_facade.to_wire(req)
    data = await http_facade.call(
        base_url=config.{f['base_url']},
        method="{r['method']}",
        path={path},
        body=body,
        api_key_header={q(r['api_key_header'])},
        api_key=config.{f['api_key']},
        idempotency_header={q(r['idempotency_header'])},
    )
    return http_facade.from_wire(data, {r['output']})
''')
    return "\n".join(out)


def gen_workflows(f: dict, rs: list[dict], src: str) -> str:
    types = sorted({r["input"] for r in rs} | {r["output"] for r in rs})
    rp = f["retry"]
    out = [header(src), '"""One workflow per route: keeps calling until success, a permanent error, or the deadline."""\n',
           "from datetime import timedelta\n",
           "from temporalio import workflow",
           "from temporalio.common import RetryPolicy\n",
           "with workflow.unsafe.imports_passed_through():",
           f"    from {f['contract_module']} import {', '.join(types)}",
           f"    from {f['handler_package']}.activities import {', '.join(r['fn'] for r in rs)}\n",
           f"RETRY = RetryPolicy(initial_interval=timedelta(seconds={rp['initial_interval_s']}), "
           f"backoff_coefficient={rp['backoff']}, maximum_interval=timedelta(seconds={rp['maximum_interval_s']}))\n"]
    for r in rs:
        out.append(f'''
@workflow.defn(name="{r['service']}.{r['operation']}")
class {r['workflow']}:
    @workflow.run
    async def run(self, req: {r['input']}) -> {r['output']}:
        return await workflow.execute_activity(
            {r['fn']},
            req,
            start_to_close_timeout=timedelta(seconds={f['attempt_timeout_s']}),
            schedule_to_close_timeout=timedelta(seconds={f['deadline_s']}),
            retry_policy=RETRY,
        )
''')
    return "\n".join(out)


def gen_worker(f: dict, rs: list[dict], src: str) -> str:
    services: dict[str, list[dict]] = {}
    for r in rs:
        services.setdefault(r["service_class"], []).append(r)
    types = sorted({r["input"] for r in rs} | {r["output"] for r in rs} | set(services))
    out = [header(src), '"""Nexus handler and worker for the API. Async operations, each backed by a workflow."""\n',
           "import asyncio", "import logging\n",
           "import nexusrpc.handler",
           "from temporalio import nexus",
           "from temporalio.worker import Worker\n",
           "from common import config",
           f"from {f['contract_module']} import {', '.join(types)}",
           f"from {f['handler_package']}.activities import {', '.join(r['fn'] for r in rs)}",
           f"from {f['handler_package']}.workflows import {', '.join(r['workflow'] for r in rs)}\n"]
    for svc, ops in services.items():
        out.append(f"\n@nexusrpc.handler.service_handler(service={svc})\nclass {svc}Handler:")
        for r in ops:
            out.append(f'''    @nexus.workflow_run_operation
    async def {r['attr']}(
        self, ctx: nexus.WorkflowRunOperationContext, req: {r['input']}
    ) -> nexus.WorkflowHandle[{r['output']}]:
        # ctx.request_id is the same on every retry of this operation, so a
        # retried start finds the same workflow instead of calling the API twice.
        return await ctx.start_workflow({r['workflow']}.run, req, id=f"{r['service']}.{r['operation']}-{{ctx.request_id}}")
''')
    handlers = ", ".join(f"{svc}Handler()" for svc in services)
    out.append(f'''
async def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    logging.getLogger("temporalio.activity").setLevel(logging.ERROR)  # http_facade logs one line per attempt
    logging.getLogger("httpx").setLevel(logging.WARNING)
    client = await config.connect(config.{f['namespace']})
    worker = Worker(
        client,
        task_queue=config.{f['task_queue']},
        workflows=[{', '.join(r['workflow'] for r in rs)}],
        activities=[{', '.join(r['fn'] for r in rs)}],
        nexus_service_handlers=[{handlers}],
    )
    logging.info("facade worker: %s / %s", config.{f['namespace']}, config.{f['task_queue']})
    await worker.run()


if __name__ == "__main__":
    asyncio.run(main())
''')
    return "\n".join(out)


if __name__ == "__main__":
    facades = yaml.safe_load(open(sys.argv[1]))
    for name, f in facades.items():
        spec = json.load(open(f["openapi"]))
        rs = routes(spec)
        pkg = Path(*f["handler_package"].split("."))
        pkg.mkdir(parents=True, exist_ok=True)
        (pkg / "__init__.py").touch()
        (pkg / "activities.py").write_text(gen_activities(f, rs, f["openapi"]))
        (pkg / "workflows.py").write_text(gen_workflows(f, rs, f["openapi"]))
        (pkg / "worker.py").write_text(gen_worker(f, rs, f["openapi"]))
        print(f"{name}: generated {pkg}/ for " + ", ".join(f"{r['service']}/{r['operation']} ({r['method']} {r['path']})" for r in rs))
