"""Turn an OpenAPI spec into a Nexus contract (.nexusrpc.yaml) for nexgen.

Only routes tagged with an `x-nexus` extension become operations, so the API's
owner decides what to publish:

    openapi_extra={"x-nexus": {"service": "notifications.v1", "operation": "send"}}

The request body schema becomes the operation input, and the 2xx response
schema becomes the output. Headers (API keys, idempotency keys) stay out of
the contract on purpose: the handler owns those.

FastAPI's schemas are tidied into the strict JSON Schema subset nexgen
accepts: titles and defaults are dropped, and an optional `X | None` field
becomes a plain optional `X`.

Usage: python scripts/openapi_to_nexus.py <openapi.json> <out.nexusrpc.yaml>
"""

import json
import re
import sys

import yaml

COMPONENT = "#/components/schemas/"
DROP_KEYS = {"title", "default"}


def pascal(name: str) -> str:
    return "".join(p.capitalize() for p in re.split(r"[^a-zA-Z0-9]+", name) if p)


def camel(name: str) -> str:
    p = pascal(name)
    return p[:1].lower() + p[1:]


def tidy(node, refs: set[str]):
    """Rewrite $refs to #/$defs/, drop noise, collapse nullable unions, collect referenced schemas."""
    if isinstance(node, list):
        return [tidy(v, refs) for v in node]
    if not isinstance(node, dict):
        return node
    if "anyOf" in node:
        branches = [b for b in node["anyOf"] if b.get("type") != "null"]
        if len(branches) == 1:  # `X | None`: optional-ness comes from `required`
            merged = {**branches[0], **{k: v for k, v in node.items() if k != "anyOf"}}
            return tidy(merged, refs)
    out = {}
    for k, v in node.items():
        if k in DROP_KEYS:
            continue
        if k == "$ref" and isinstance(v, str) and v.startswith(COMPONENT):
            name = v.removeprefix(COMPONENT)
            refs.add(name)
            out[k] = "#/$defs/" + name
        else:
            out[k] = tidy(v, refs)
    if "properties" in out and out.get("type") == "object":
        out.setdefault("additionalProperties", False)
    return out


def convert(spec: dict) -> dict:
    services: dict[str, dict] = {}
    refs: set[str] = set()
    for path, methods in spec.get("paths", {}).items():
        for method, op in methods.items():
            nexus = op.get("x-nexus")
            if not nexus:
                continue
            body = op["requestBody"]["content"]["application/json"]["schema"]
            ok = next(r for code, r in op["responses"].items() if code.startswith("2"))
            out = ok["content"]["application/json"]["schema"]
            service_key = pascal(nexus["service"].split(".")[0])  # notifications.v1 -> Notifications
            svc = services.setdefault(service_key, {
                "fqn": nexus["service"],  # the service name on the wire
                "description": spec["info"]["title"],
                "operations": {},
            })
            svc["operations"][camel(nexus["operation"])] = {
                "fqn": nexus["operation"],  # the operation name on the wire
                "description": f"{op.get('summary') or op.get('description', '').strip()} ({method.upper()} {path})",
                "input": tidy(body, refs),
                "output": tidy(out, refs),
            }

    schemas = spec.get("components", {}).get("schemas", {})
    defs: dict[str, dict] = {}
    pending = set(refs)
    while pending:  # follow nested references
        name = pending.pop()
        found: set[str] = set()
        defs[name] = tidy(schemas[name], found)
        pending |= found - defs.keys()

    # nexgen keeps only object types in $defs; inline scalars such as string enums.
    scalars = {n: d for n, d in defs.items() if d.get("type") != "object"}

    def inline(node):
        if isinstance(node, list):
            return [inline(v) for v in node]
        if not isinstance(node, dict):
            return node
        ref = node.get("$ref", "").removeprefix("#/$defs/")
        if ref in scalars:
            return {**scalars[ref], **{k: v for k, v in node.items() if k != "$ref"}}
        return {k: inline(v) for k, v in node.items()}

    return {
        "nexusrpc": "1.0.0",
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "services": inline(services),
        "$defs": {n: inline(d) for n, d in sorted(defs.items()) if n not in scalars},
    }


if __name__ == "__main__":
    src, dst = sys.argv[1], sys.argv[2]
    contract = convert(json.load(open(src)))
    with open(dst, "w") as f:
        f.write(f"# GENERATED by scripts/openapi_to_nexus.py from {src}. Do not edit.\n# Regenerate with: make codegen\n")
        yaml.safe_dump(contract, f, sort_keys=False, width=100)
    print(f"wrote {dst}: " + ", ".join(
        f"{d['fqn']}/{o['fqn']}" for d in contract["services"].values() for o in d["operations"].values()))
