"""Plan Nexus endpoints for every environment and region, and optionally write Terraform.

Two strategies, both without a router worker:
  per-capability  one endpoint per service per stamp      notifications-prod-ch
  per-team        one endpoint per publishing team per stamp; the team's worker
                  registers all of its services on one task queue   documents-prod-ch

Allowlists keep stamps apart: an endpoint in prod-ch only accepts callers in prod-ch.

Usage:
  python scripts/plan_endpoints.py deploy/endpoints.yaml [--strategy per-capability|per-team]
                                   [--terraform OUT.tf] [--project CAPABILITIES TEAMS]
"""

import argparse
import math

import yaml

DEFAULT_LIMIT = 100  # endpoints per account by default; can be raised (see docs.temporal.io/cloud/limits)


def plan(inv: dict, strategy: str) -> list[dict]:
    endpoints = []
    for stamp in inv["stamps"]:
        for team, pub in inv["publishers"].items():
            groups = [[svc] for svc in pub["services"]] if strategy == "per-capability" else [pub["services"]]
            for services in groups:
                base = services[0].split(".")[0] if strategy == "per-capability" else team
                allowed = sorted(
                    c["namespace"].format(stamp=stamp)
                    for c in inv["callers"].values()
                    if set(c["calls"]) & set(services)
                )
                endpoints.append({
                    "name": f"{base}-{stamp}",
                    "stamp": stamp,
                    "services": services,
                    "namespace": pub["namespace"].format(stamp=stamp),
                    "task_queue": pub["task_queue"],
                    "allowed": allowed,
                })
    return endpoints


def terraform(endpoints: list[dict]) -> str:
    out = ['# GENERATED by scripts/plan_endpoints.py. Namespace IDs are "<name>.<account id>".',
           'variable "account_id" { type = string }', ""]
    for e in endpoints:
        if not e["allowed"]:
            out.append(f"# {e['name']}: no callers yet, so not created\n")
            continue
        res = e["name"].replace("-", "_")
        allowed = ",\n    ".join(f'"{ns}.${{var.account_id}}"' for ns in e["allowed"])
        out.append(f'''resource "temporalcloud_nexus_endpoint" "{res}" {{
  name        = "{e['name']}"
  description = "{', '.join(e['services'])}"
  worker_target = {{
    namespace_id = "{e['namespace']}.${{var.account_id}}"
    task_queue   = "{e['task_queue']}"
  }}
  allowed_caller_namespaces = [
    {allowed}
  ]
}}
''')
    return "\n".join(out)


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("inventory")
    p.add_argument("--strategy", choices=["per-capability", "per-team"], default=None)
    p.add_argument("--terraform", metavar="OUT.tf")
    p.add_argument("--project", nargs=2, type=int, metavar=("CAPABILITIES", "TEAMS"), default=(20, 8))
    a = p.parse_args()
    inv = yaml.safe_load(open(a.inventory))
    stamps = inv["stamps"]

    print(f"Stamps ({len(stamps)}): {', '.join(stamps)}\n")
    for strategy in [a.strategy] if a.strategy else ["per-capability", "per-team"]:
        eps = plan(inv, strategy)
        print(f"{strategy}: {len(eps)} endpoints")
        for e in eps:
            if e["stamp"] == stamps[-1]:  # one stamp is enough to show the shape
                print(f"  {e['name']:<28} {', '.join(e['services']):<30} -> {e['namespace']} / {e['task_queue']}")
                print(f"  {'':<28} allow: {', '.join(e['allowed']) or '(no callers yet: not created)'}")
        print(f"  (same shape repeated for every stamp)\n")

    caps, teams = a.project
    s = len(stamps)
    print(f"At {caps} capabilities owned by {teams} teams across {s} stamps:")
    print(f"  per-capability: {caps * s:>4} endpoints   per-team: {teams * s:>4} endpoints"
          f"   default limit: {DEFAULT_LIMIT} per account, raisable")
    print(f"  per-capability reaches the default limit at {math.floor(DEFAULT_LIMIT / s)} capabilities")

    if a.terraform:
        eps = plan(inv, a.strategy or "per-capability")
        open(a.terraform, "w").write(terraform(eps))
        print(f"\nwrote {a.terraform} ({len(eps)} endpoints, {a.strategy or 'per-capability'})")


if __name__ == "__main__":
    main()
