# GENERATED by scripts/gen_facade.py from contracts/openapi/notification-api.json. Do not edit.
# Regenerate with: make codegen

"""HTTP calls to the API, one activity per published route."""

from temporalio import activity

from common import config, http_facade
from contracts.gen.notifications import NotificationReceipt, NotificationRequest


@activity.defn(name="notifications.v1.send")
async def notifications_send(req: NotificationRequest) -> NotificationReceipt:
    """POST /v1/notifications"""
    body = http_facade.to_wire(req)
    data = await http_facade.call(
        base_url=config.NOTIFICATION_API_URL,
        method="POST",
        path="/v1/notifications",
        body=body,
        api_key_header="X-API-Key",
        api_key=config.NOTIFICATION_API_KEY,
        idempotency_header="Idempotency-Key",
    )
    return http_facade.from_wire(data, NotificationReceipt)
