# GENERATED by scripts/gen_facade.py from contracts/openapi/notification-api.json. Do not edit.
# Regenerate with: make codegen

"""Nexus handler and worker for the API. Async operations, each backed by a workflow."""

import asyncio
import logging

import nexusrpc.handler
from temporalio import nexus
from temporalio.worker import Worker

from common import config
from contracts.gen.notifications import NotificationReceipt, NotificationRequest, Notifications
from handlers.notifications.activities import notifications_send
from handlers.notifications.workflows import NotificationsSendWorkflow


@nexusrpc.handler.service_handler(service=Notifications)
class NotificationsHandler:
    @nexus.workflow_run_operation
    async def send(
        self, ctx: nexus.WorkflowRunOperationContext, req: NotificationRequest
    ) -> nexus.WorkflowHandle[NotificationReceipt]:
        # ctx.request_id is the same on every retry of this operation, so a
        # retried start finds the same workflow instead of calling the API twice.
        return await ctx.start_workflow(NotificationsSendWorkflow.run, req, id=f"notifications.v1.send-{ctx.request_id}")


async def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    logging.getLogger("temporalio.activity").setLevel(logging.ERROR)  # http_facade logs one line per attempt
    logging.getLogger("httpx").setLevel(logging.WARNING)
    client = await config.connect(config.NOTIFY_NAMESPACE)
    worker = Worker(
        client,
        task_queue=config.NOTIFY_TASK_QUEUE,
        workflows=[NotificationsSendWorkflow],
        activities=[notifications_send],
        nexus_service_handlers=[NotificationsHandler()],
    )
    logging.info("facade worker: %s / %s", config.NOTIFY_NAMESPACE, config.NOTIFY_TASK_QUEUE)
    await worker.run()


if __name__ == "__main__":
    asyncio.run(main())
