# GENERATED by scripts/gen_facade.py from contracts/openapi/notification-api.json. Do not edit.
# Regenerate with: make codegen

"""One workflow per route: keeps calling until success, a permanent error, or the deadline."""

from datetime import timedelta

from temporalio import workflow
from temporalio.common import RetryPolicy

with workflow.unsafe.imports_passed_through():
    from contracts.gen.notifications import NotificationReceipt, NotificationRequest
    from handlers.notifications.activities import notifications_send

RETRY = RetryPolicy(initial_interval=timedelta(seconds=1), backoff_coefficient=2.0, maximum_interval=timedelta(seconds=10))


@workflow.defn(name="notifications.v1.send")
class NotificationsSendWorkflow:
    @workflow.run
    async def run(self, req: NotificationRequest) -> NotificationReceipt:
        return await workflow.execute_activity(
            notifications_send,
            req,
            start_to_close_timeout=timedelta(seconds=10),
            schedule_to_close_timeout=timedelta(seconds=3600),
            retry_policy=RETRY,
        )
